#! /bin/sh
# test_env: set up the environment needed to run tests:
# - set up a private bus
# - run a test server on it


TMPDIR=`mktemp -d dbus.test.XXXXXX`
RM_FILES="$RM_FILES $TMPDIR"
# Clean up at exit.
trap "rm -rf \$RM_FILES" EXIT TERM INT

export XDG_DATA_HOME="$TMPDIR"
#export DBUS_VERBOSE=1
#export RUBYOPT="-d"
export RUBYOPT="$RUBYOPT -w"
./dbus-launch-simple \
    ./test_server -n org.ruby.service -Q /org/ruby/MyInstance -q org.ruby.SampleInterface.Quit \
	./service_newapi.rb \
	-- \
	"$@"
