#! /bin/bash
# test_env: set up the environment needed to run tests:
# - set up a private bus
# - run a test server on it

#export DBUS_VERBOSE=1
#export RUBYOPT="-d"
export RUBYOPT="$RUBYOPT -w"
DIR=$(dirname $0)
$DIR/test_server \
	$DIR/../service_newapi.rb \
	-- \
	dbus-run-session --config-file=$(dirname $0)/dbus-limited-session.conf \
	"$@"
